replicaCount: 2

image:
  repository: farah729/depi
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /readiness
    port: 5000
  initialDelaySeconds: 30
  timeoutSeconds: 5

serviceAccount:
  create: true
  annotations: {}
  automount: true

ingress:
  enabled: true
  name: ""
  nginx: 
    class: "nginx"
  annotations: {}
  pathType: ImplementationSpecific
  paths:
    - /
  hosts:
    - host: my-flask-app.local
      paths:
        - /
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
