name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flask pytz requests pytest

      - name: Lint with pylint
        run: |
          pylint --disable=all --enable=F,E,R,W app.py

      - name: Test with pytest
        run: |
          pytest

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t farah729/depi:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u farah729 --password-stdin

      - name: Push Docker image
        run: |
          docker push farah729/depi:latest

